version: '3.7'

networks:
  default:
    name: urbs-network
    driver: bridge

services:
  jupyterlab:
    container_name: urbs-jupyterlab
    restart: unless-stopped
    user: root
    build: .
    image: utfpr/jupyterlab:latest
    working_dir: /opt/urbs-data-processing/
    ports:
      - 8085:8085
      - 4040:4040
    volumes:
      - .:/opt/urbs-data-processing/
      - /mnt/work/datalake:/data/
      - /mnt/work/database/mysql:/var/lib/mysql/
      - /mnt/work/database/mysql-files:/var/lib/mysql-files/
    networks:
      - default
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: busanalysis_dw      