version: '3.7'

networks:
  urbs-network:
    driver: bridge

services:
  mysql:
    container_name: urbs-data-mysql
    image: mysql:8.0.39
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - '3307:3306'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
      - /mnt/work/database/mysql:/var/lib/mysql/
      - /mnt/work/database/mysql-files:/var/lib/mysql-files/
    networks:
      - urbs-network

  jupyterlab:
    container_name: urbs-jupyterlab
    restart: always
    user: root
    build: .
    image: utfpr/jupyterlab:latest
    working_dir: /opt/urbs-data-processing/
    ports:
      - 8085:8085
      - 4040:4040
    volumes:
      - .:/opt/urbs-data-processing/
      - /mnt/work/datalake:/data/
      - /mnt/work/database/mysql:/var/lib/mysql/
      - /mnt/work/database/mysql-files:/var/lib/mysql-files/
    networks:
      - urbs-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: busanalysis_dw      